Fix failing unit test in other_types_test.go
The test `github.com/sijms/go-ora/v2/converters/generatefloat` is failing for me:

```
~/git/static/go-ora/v2/converters$ go clean -testcache && go test
--- FAIL: TestBinaryFloat (0.00s)
    other_types_test.go:32: expected -134.45, got -134.44
FAIL
exit status 1
FAIL	github.com/sijms/go-ora/v2/converters	0.033s
```

This change updates the expected value, causing the test to succeed:

```
~/git/static/go-ora/v2/converters$ go clean -testcache && go test
PASS
ok  	github.com/sijms/go-ora/v2/converters	0.033s
```